#include "Globals.h"
#include "Application.h"
#include "ModuleCollision.h"
#include "ModulePlayer.h"

ModuleCollision::ModuleCollision(Application* app, bool start_enabled) : Module(app, start_enabled)
{
	debug = false;
    //P1(BLUE)
	matrix[COLLIDER_PLAYER_BODY][COLLIDER_PLAYER_BODY] = false;
	matrix[COLLIDER_PLAYER_BODY][COLLIDER_PLAYER_HEAD] = false;
	matrix[COLLIDER_PLAYER_BODY][COLLIDER_PLAYER_FEET] = false;
	matrix[COLLIDER_PLAYER_BODY][COLLIDER_PLAYER_BLOCK] = false;
	matrix[COLLIDER_PLAYER_BODY][COLLIDER_ENEMY_BLOCK] = false;
	matrix[COLLIDER_PLAYER_BODY][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_PLAYER_BODY][COLLIDER_ENEMY] = false;
	matrix[COLLIDER_PLAYER_BODY][COLLIDER_PLAYER_WEAKATTACK] = false;
	matrix[COLLIDER_PLAYER_BODY][COLLIDER_PLAYER_MIDATTACK] = false;
	matrix[COLLIDER_PLAYER_BODY][COLLIDER_PLAYER_STRONGATTACK] = false;
	matrix[COLLIDER_PLAYER_BODY][COLLIDER_ENEMY_WEAKATTACK] = true;
	matrix[COLLIDER_PLAYER_BODY][COLLIDER_ENEMY_MIDATTACK] = true;
	matrix[COLLIDER_PLAYER_BODY][COLLIDER_ENEMY_STRONGATTACK] = true;
	matrix[COLLIDER_PLAYER_BODY][COLLIDER_ENEMY_BODY] = false;
	matrix[COLLIDER_PLAYER_BODY][COLLIDER_ENEMY_HEAD] = false;
	matrix[COLLIDER_PLAYER_BODY][COLLIDER_ENEMY_FEET] = false;

	matrix[COLLIDER_PLAYER_HEAD][COLLIDER_PLAYER_BODY] = false;
	matrix[COLLIDER_PLAYER_HEAD][COLLIDER_PLAYER_HEAD] = false;
	matrix[COLLIDER_PLAYER_HEAD][COLLIDER_PLAYER_FEET] = false;
	matrix[COLLIDER_PLAYER_HEAD][COLLIDER_PLAYER_BLOCK] = false;
	matrix[COLLIDER_PLAYER_HEAD][COLLIDER_ENEMY_BLOCK] = false;
	matrix[COLLIDER_PLAYER_HEAD][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_PLAYER_HEAD][COLLIDER_ENEMY] = false;
	matrix[COLLIDER_PLAYER_HEAD][COLLIDER_PLAYER_WEAKATTACK] = false;
	matrix[COLLIDER_PLAYER_HEAD][COLLIDER_PLAYER_MIDATTACK] = false;
	matrix[COLLIDER_PLAYER_HEAD][COLLIDER_PLAYER_STRONGATTACK] = false;
	matrix[COLLIDER_PLAYER_HEAD][COLLIDER_ENEMY_WEAKATTACK] = true;
	matrix[COLLIDER_PLAYER_HEAD][COLLIDER_ENEMY_MIDATTACK] = true;
	matrix[COLLIDER_PLAYER_HEAD][COLLIDER_ENEMY_STRONGATTACK] = true;
	matrix[COLLIDER_PLAYER_HEAD][COLLIDER_ENEMY_BODY] = false;
	matrix[COLLIDER_PLAYER_HEAD][COLLIDER_ENEMY_HEAD] = false;
	matrix[COLLIDER_PLAYER_HEAD][COLLIDER_ENEMY_FEET] = false;

	matrix[COLLIDER_PLAYER_FEET][COLLIDER_PLAYER_BODY] = false;
	matrix[COLLIDER_PLAYER_FEET][COLLIDER_PLAYER_HEAD] = false;
	matrix[COLLIDER_PLAYER_FEET][COLLIDER_PLAYER_FEET] = false;
	matrix[COLLIDER_PLAYER_FEET][COLLIDER_PLAYER_BLOCK] = false;
	matrix[COLLIDER_PLAYER_FEET][COLLIDER_ENEMY_BLOCK] = false;
	matrix[COLLIDER_PLAYER_FEET][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_PLAYER_FEET][COLLIDER_ENEMY] = false;
	matrix[COLLIDER_PLAYER_FEET][COLLIDER_PLAYER_WEAKATTACK] = false;
	matrix[COLLIDER_PLAYER_FEET][COLLIDER_PLAYER_MIDATTACK] = false;
	matrix[COLLIDER_PLAYER_FEET][COLLIDER_PLAYER_STRONGATTACK] = false;
	matrix[COLLIDER_PLAYER_FEET][COLLIDER_ENEMY_WEAKATTACK] = true;
	matrix[COLLIDER_PLAYER_FEET][COLLIDER_ENEMY_MIDATTACK] = true;
	matrix[COLLIDER_PLAYER_FEET][COLLIDER_ENEMY_STRONGATTACK] = true;
	matrix[COLLIDER_PLAYER_FEET][COLLIDER_ENEMY_BODY] = false;
	matrix[COLLIDER_PLAYER_FEET][COLLIDER_ENEMY_HEAD] = false;
	matrix[COLLIDER_PLAYER_FEET][COLLIDER_ENEMY_FEET] = false;

	//P1 BLOCK (YELLOW)

	matrix[COLLIDER_PLAYER_BLOCK][COLLIDER_PLAYER_BODY] = false;
	matrix[COLLIDER_PLAYER_BLOCK][COLLIDER_PLAYER_HEAD] = false;
	matrix[COLLIDER_PLAYER_BLOCK][COLLIDER_PLAYER_FEET] = false;
	matrix[COLLIDER_PLAYER_BLOCK][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_PLAYER_BLOCK][COLLIDER_ENEMY] = false;
	matrix[COLLIDER_PLAYER_BLOCK][COLLIDER_PLAYER_WEAKATTACK] = false;
	matrix[COLLIDER_PLAYER_BLOCK][COLLIDER_PLAYER_MIDATTACK] = false;
	matrix[COLLIDER_PLAYER_BLOCK][COLLIDER_PLAYER_STRONGATTACK] = false;
	matrix[COLLIDER_PLAYER_BLOCK][COLLIDER_ENEMY_WEAKATTACK] = true;
	matrix[COLLIDER_PLAYER_BLOCK][COLLIDER_ENEMY_MIDATTACK] = true;
	matrix[COLLIDER_PLAYER_BLOCK][COLLIDER_ENEMY_STRONGATTACK] = true;
	matrix[COLLIDER_PLAYER_BLOCK][COLLIDER_ENEMY_BODY] = false;
	matrix[COLLIDER_PLAYER_BLOCK][COLLIDER_ENEMY_HEAD] = false;
	matrix[COLLIDER_PLAYER_BLOCK][COLLIDER_ENEMY_FEET] = false;

	//P1 BLOCK_CROUCH (YELLOW)

	matrix[COLLIDER_PLAYER_BLOCK_CROUCH][COLLIDER_PLAYER_BODY] = false;
	matrix[COLLIDER_PLAYER_BLOCK_CROUCH][COLLIDER_PLAYER_HEAD] = false;
	matrix[COLLIDER_PLAYER_BLOCK_CROUCH][COLLIDER_PLAYER_FEET] = false;
	matrix[COLLIDER_PLAYER_BLOCK_CROUCH][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_PLAYER_BLOCK_CROUCH][COLLIDER_ENEMY] = false;
	matrix[COLLIDER_PLAYER_BLOCK_CROUCH][COLLIDER_PLAYER_WEAKATTACK] = false;
	matrix[COLLIDER_PLAYER_BLOCK_CROUCH][COLLIDER_PLAYER_MIDATTACK] = false;
	matrix[COLLIDER_PLAYER_BLOCK_CROUCH][COLLIDER_PLAYER_STRONGATTACK] = false;
	matrix[COLLIDER_PLAYER_BLOCK_CROUCH][COLLIDER_ENEMY_WEAKATTACK] = true;
	matrix[COLLIDER_PLAYER_BLOCK_CROUCH][COLLIDER_ENEMY_MIDATTACK] = true;
	matrix[COLLIDER_PLAYER_BLOCK_CROUCH][COLLIDER_ENEMY_STRONGATTACK] = true;
	matrix[COLLIDER_PLAYER_BLOCK_CROUCH][COLLIDER_ENEMY_BODY] = false;
	matrix[COLLIDER_PLAYER_BLOCK_CROUCH][COLLIDER_ENEMY_HEAD] = false;
	matrix[COLLIDER_PLAYER_BLOCK_CROUCH][COLLIDER_ENEMY_FEET] = false;



	//Personaje (GREEN)

	matrix[COLLIDER_PLAYER][COLLIDER_PLAYER_BODY] = false;
	matrix[COLLIDER_PLAYER][COLLIDER_PLAYER_HEAD] = false;
	matrix[COLLIDER_PLAYER][COLLIDER_PLAYER_FEET] = false;
	matrix[COLLIDER_PLAYER][COLLIDER_PLAYER_BLOCK] = false;
	matrix[COLLIDER_PLAYER][COLLIDER_ENEMY_BLOCK] = false;
	matrix[COLLIDER_PLAYER][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_PLAYER][COLLIDER_ENEMY] = true;
	matrix[COLLIDER_PLAYER][COLLIDER_PLAYER_WEAKATTACK] = false;
	matrix[COLLIDER_PLAYER][COLLIDER_PLAYER_MIDATTACK] = false;
	matrix[COLLIDER_PLAYER][COLLIDER_PLAYER_STRONGATTACK] = false;
	matrix[COLLIDER_PLAYER][COLLIDER_ENEMY_WEAKATTACK] = false;
	matrix[COLLIDER_PLAYER][COLLIDER_ENEMY_MIDATTACK] = false;
	matrix[COLLIDER_PLAYER][COLLIDER_ENEMY_STRONGATTACK] = false;
	matrix[COLLIDER_PLAYER][COLLIDER_ENEMY_BODY] = false;
	matrix[COLLIDER_PLAYER][COLLIDER_ENEMY_HEAD] = false;
	matrix[COLLIDER_PLAYER][COLLIDER_ENEMY_FEET] = false;

	//Enemy (GREEN)

	matrix[COLLIDER_ENEMY][COLLIDER_PLAYER_BODY] = false;
	matrix[COLLIDER_ENEMY][COLLIDER_PLAYER_HEAD] = false;
	matrix[COLLIDER_ENEMY][COLLIDER_PLAYER_FEET] = false;
	matrix[COLLIDER_ENEMY][COLLIDER_PLAYER_BLOCK] = false;
	matrix[COLLIDER_ENEMY][COLLIDER_ENEMY_BLOCK] = false;
	matrix[COLLIDER_ENEMY][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_ENEMY][COLLIDER_ENEMY] = true;
	matrix[COLLIDER_ENEMY][COLLIDER_PLAYER_WEAKATTACK] = false;
	matrix[COLLIDER_ENEMY][COLLIDER_PLAYER_MIDATTACK] = false;
	matrix[COLLIDER_ENEMY][COLLIDER_PLAYER_STRONGATTACK] = false;
	matrix[COLLIDER_ENEMY][COLLIDER_ENEMY_WEAKATTACK] = false;
	matrix[COLLIDER_ENEMY][COLLIDER_ENEMY_MIDATTACK] = false;
	matrix[COLLIDER_ENEMY][COLLIDER_ENEMY_STRONGATTACK] = false;
	matrix[COLLIDER_ENEMY][COLLIDER_ENEMY_BODY] = false;
	matrix[COLLIDER_ENEMY][COLLIDER_ENEMY_HEAD] = false;
	matrix[COLLIDER_ENEMY][COLLIDER_ENEMY_FEET] = false;

	//Attack Player1 (RED)

	matrix[COLLIDER_PLAYER_WEAKATTACK][COLLIDER_PLAYER_BODY] = false;
	matrix[COLLIDER_PLAYER_WEAKATTACK][COLLIDER_PLAYER_HEAD] = false;
	matrix[COLLIDER_PLAYER_WEAKATTACK][COLLIDER_PLAYER_FEET] = false;
	matrix[COLLIDER_PLAYER_WEAKATTACK][COLLIDER_PLAYER_BLOCK] = false;
	matrix[COLLIDER_PLAYER_WEAKATTACK][COLLIDER_ENEMY_BLOCK] = true;
	matrix[COLLIDER_PLAYER_WEAKATTACK][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_PLAYER_WEAKATTACK][COLLIDER_ENEMY] = false;
	matrix[COLLIDER_PLAYER_WEAKATTACK][COLLIDER_ENEMY_WEAKATTACK] = false;
	matrix[COLLIDER_PLAYER_WEAKATTACK][COLLIDER_ENEMY_MIDATTACK] = false;
	matrix[COLLIDER_PLAYER_WEAKATTACK][COLLIDER_ENEMY_STRONGATTACK] = false;
	matrix[COLLIDER_PLAYER_WEAKATTACK][COLLIDER_ENEMY_BODY] = true;
	matrix[COLLIDER_PLAYER_WEAKATTACK][COLLIDER_ENEMY_HEAD] = true;
	matrix[COLLIDER_PLAYER_WEAKATTACK][COLLIDER_ENEMY_FEET] = true;

	matrix[COLLIDER_PLAYER_MIDATTACK][COLLIDER_PLAYER_BODY] = false;
	matrix[COLLIDER_PLAYER_MIDATTACK][COLLIDER_PLAYER_HEAD] = false;
	matrix[COLLIDER_PLAYER_MIDATTACK][COLLIDER_PLAYER_FEET] = false;
	matrix[COLLIDER_PLAYER_MIDATTACK][COLLIDER_PLAYER_BLOCK] = false;
	matrix[COLLIDER_PLAYER_MIDATTACK][COLLIDER_ENEMY_BLOCK] = true;
	matrix[COLLIDER_PLAYER_MIDATTACK][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_PLAYER_MIDATTACK][COLLIDER_ENEMY] = false;
	matrix[COLLIDER_PLAYER_MIDATTACK][COLLIDER_ENEMY_WEAKATTACK] = false;
	matrix[COLLIDER_PLAYER_MIDATTACK][COLLIDER_ENEMY_MIDATTACK] = false;
	matrix[COLLIDER_PLAYER_MIDATTACK][COLLIDER_ENEMY_STRONGATTACK] = false;
	matrix[COLLIDER_PLAYER_MIDATTACK][COLLIDER_ENEMY_BODY] = true;
	matrix[COLLIDER_PLAYER_MIDATTACK][COLLIDER_ENEMY_HEAD] = true;
	matrix[COLLIDER_PLAYER_MIDATTACK][COLLIDER_ENEMY_FEET] = true;

	matrix[COLLIDER_PLAYER_STRONGATTACK][COLLIDER_PLAYER_BODY] = false;
	matrix[COLLIDER_PLAYER_STRONGATTACK][COLLIDER_PLAYER_HEAD] = false;
	matrix[COLLIDER_PLAYER_STRONGATTACK][COLLIDER_PLAYER_FEET] = false;
	matrix[COLLIDER_PLAYER_STRONGATTACK][COLLIDER_PLAYER_BLOCK] = false;
	matrix[COLLIDER_PLAYER_STRONGATTACK][COLLIDER_ENEMY_BLOCK] = true;
	matrix[COLLIDER_PLAYER_STRONGATTACK][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_PLAYER_STRONGATTACK][COLLIDER_ENEMY] = false;
	matrix[COLLIDER_PLAYER_STRONGATTACK][COLLIDER_ENEMY_WEAKATTACK] = false;
	matrix[COLLIDER_PLAYER_STRONGATTACK][COLLIDER_ENEMY_MIDATTACK] = false;
	matrix[COLLIDER_PLAYER_STRONGATTACK][COLLIDER_ENEMY_STRONGATTACK] = false;
	matrix[COLLIDER_PLAYER_STRONGATTACK][COLLIDER_ENEMY_BODY] = true;
	matrix[COLLIDER_PLAYER_STRONGATTACK][COLLIDER_ENEMY_HEAD] = true;
	matrix[COLLIDER_PLAYER_STRONGATTACK][COLLIDER_ENEMY_FEET] = true;

	//Attack Player 2 (RED)

	matrix[COLLIDER_ENEMY_WEAKATTACK][COLLIDER_PLAYER_BODY] = true;
	matrix[COLLIDER_ENEMY_WEAKATTACK][COLLIDER_PLAYER_HEAD] = true;
	matrix[COLLIDER_ENEMY_WEAKATTACK][COLLIDER_PLAYER_FEET] = true;
	matrix[COLLIDER_ENEMY_WEAKATTACK][COLLIDER_PLAYER_BLOCK] = true;
	matrix[COLLIDER_ENEMY_WEAKATTACK][COLLIDER_ENEMY_BLOCK] = false;
	matrix[COLLIDER_ENEMY_WEAKATTACK][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_ENEMY_WEAKATTACK][COLLIDER_ENEMY] = false;
	matrix[COLLIDER_ENEMY_WEAKATTACK][COLLIDER_PLAYER_WEAKATTACK] = false;
	matrix[COLLIDER_ENEMY_WEAKATTACK][COLLIDER_PLAYER_MIDATTACK] = false;
	matrix[COLLIDER_ENEMY_WEAKATTACK][COLLIDER_PLAYER_STRONGATTACK] = false;
	matrix[COLLIDER_ENEMY_WEAKATTACK][COLLIDER_ENEMY_BODY] = false;
	matrix[COLLIDER_ENEMY_WEAKATTACK][COLLIDER_ENEMY_HEAD] = false;
	matrix[COLLIDER_ENEMY_WEAKATTACK][COLLIDER_ENEMY_FEET] = false;

	matrix[COLLIDER_ENEMY_MIDATTACK][COLLIDER_PLAYER_BODY] = true;
	matrix[COLLIDER_ENEMY_MIDATTACK][COLLIDER_PLAYER_HEAD] = true;
	matrix[COLLIDER_ENEMY_MIDATTACK][COLLIDER_PLAYER_FEET] = true;
	matrix[COLLIDER_ENEMY_MIDATTACK][COLLIDER_PLAYER_BLOCK] = true;
	matrix[COLLIDER_ENEMY_MIDATTACK][COLLIDER_ENEMY_BLOCK] = false;
	matrix[COLLIDER_ENEMY_MIDATTACK][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_ENEMY_MIDATTACK][COLLIDER_ENEMY] = false;
	matrix[COLLIDER_ENEMY_MIDATTACK][COLLIDER_PLAYER_WEAKATTACK] = false;
	matrix[COLLIDER_ENEMY_MIDATTACK][COLLIDER_PLAYER_MIDATTACK] = false;
	matrix[COLLIDER_ENEMY_MIDATTACK][COLLIDER_PLAYER_STRONGATTACK] = false;
	matrix[COLLIDER_ENEMY_MIDATTACK][COLLIDER_ENEMY_BODY] = false;
	matrix[COLLIDER_ENEMY_MIDATTACK][COLLIDER_ENEMY_HEAD] = false;
	matrix[COLLIDER_ENEMY_MIDATTACK][COLLIDER_ENEMY_FEET] = false;

	matrix[COLLIDER_ENEMY_STRONGATTACK][COLLIDER_PLAYER_BODY] = true;
	matrix[COLLIDER_ENEMY_STRONGATTACK][COLLIDER_PLAYER_HEAD] = true;
	matrix[COLLIDER_ENEMY_STRONGATTACK][COLLIDER_PLAYER_FEET] = true;
	matrix[COLLIDER_ENEMY_STRONGATTACK][COLLIDER_PLAYER_BLOCK] = true;
	matrix[COLLIDER_ENEMY_STRONGATTACK][COLLIDER_ENEMY_BLOCK] = false;
	matrix[COLLIDER_ENEMY_STRONGATTACK][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_ENEMY_STRONGATTACK][COLLIDER_ENEMY] = false;
	matrix[COLLIDER_ENEMY_STRONGATTACK][COLLIDER_PLAYER_WEAKATTACK] = false;
	matrix[COLLIDER_ENEMY_STRONGATTACK][COLLIDER_PLAYER_MIDATTACK] = false;
	matrix[COLLIDER_ENEMY_STRONGATTACK][COLLIDER_PLAYER_STRONGATTACK] = false;
	matrix[COLLIDER_ENEMY_STRONGATTACK][COLLIDER_ENEMY_BODY] = false;
	matrix[COLLIDER_ENEMY_STRONGATTACK][COLLIDER_ENEMY_HEAD] = false;
	matrix[COLLIDER_ENEMY_STRONGATTACK][COLLIDER_ENEMY_FEET] = false;




	//P2(BLUE)

	matrix[COLLIDER_ENEMY_BODY][COLLIDER_PLAYER_BODY] = false;
	matrix[COLLIDER_ENEMY_BODY][COLLIDER_PLAYER_HEAD] = false;
	matrix[COLLIDER_ENEMY_BODY][COLLIDER_PLAYER_FEET] = false;
	matrix[COLLIDER_ENEMY_BODY][COLLIDER_PLAYER_BLOCK] = false;
	matrix[COLLIDER_ENEMY_BODY][COLLIDER_ENEMY_BLOCK] = false;
	matrix[COLLIDER_ENEMY_BODY][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_ENEMY_BODY][COLLIDER_ENEMY] = false;
	matrix[COLLIDER_ENEMY_BODY][COLLIDER_PLAYER_WEAKATTACK] = true;
	matrix[COLLIDER_ENEMY_BODY][COLLIDER_PLAYER_MIDATTACK] = true;
	matrix[COLLIDER_ENEMY_BODY][COLLIDER_PLAYER_STRONGATTACK] = true;
	matrix[COLLIDER_ENEMY_BODY][COLLIDER_ENEMY_WEAKATTACK] = false;
	matrix[COLLIDER_ENEMY_BODY][COLLIDER_ENEMY_MIDATTACK] = false;
	matrix[COLLIDER_ENEMY_BODY][COLLIDER_ENEMY_STRONGATTACK] = false;
	matrix[COLLIDER_ENEMY_BODY][COLLIDER_ENEMY_BODY] = false;
	matrix[COLLIDER_ENEMY_BODY][COLLIDER_ENEMY_HEAD] = false;
	matrix[COLLIDER_ENEMY_BODY][COLLIDER_ENEMY_FEET] = false;

	matrix[COLLIDER_ENEMY_HEAD][COLLIDER_PLAYER_BODY] = false;
	matrix[COLLIDER_ENEMY_HEAD][COLLIDER_PLAYER_HEAD] = false;
	matrix[COLLIDER_ENEMY_HEAD][COLLIDER_PLAYER_FEET] = false;
	matrix[COLLIDER_ENEMY_HEAD][COLLIDER_PLAYER_BLOCK] = false;
	matrix[COLLIDER_ENEMY_HEAD][COLLIDER_ENEMY_BLOCK] = false;
	matrix[COLLIDER_ENEMY_HEAD][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_ENEMY_HEAD][COLLIDER_ENEMY] = false;
	matrix[COLLIDER_ENEMY_HEAD][COLLIDER_PLAYER_WEAKATTACK] = true;
	matrix[COLLIDER_ENEMY_HEAD][COLLIDER_PLAYER_MIDATTACK] = true;
	matrix[COLLIDER_ENEMY_HEAD][COLLIDER_PLAYER_STRONGATTACK] = true;
	matrix[COLLIDER_ENEMY_HEAD][COLLIDER_ENEMY_WEAKATTACK] = false;
	matrix[COLLIDER_ENEMY_HEAD][COLLIDER_ENEMY_MIDATTACK] = false;
	matrix[COLLIDER_ENEMY_HEAD][COLLIDER_ENEMY_STRONGATTACK] = false;
	matrix[COLLIDER_ENEMY_HEAD][COLLIDER_ENEMY_BODY] = false;
	matrix[COLLIDER_ENEMY_HEAD][COLLIDER_ENEMY_HEAD] = false;
	matrix[COLLIDER_ENEMY_HEAD][COLLIDER_ENEMY_FEET] = false;

	matrix[COLLIDER_ENEMY_FEET][COLLIDER_PLAYER_BODY] = false;
	matrix[COLLIDER_ENEMY_FEET][COLLIDER_PLAYER_HEAD] = false;
	matrix[COLLIDER_ENEMY_FEET][COLLIDER_PLAYER_FEET] = false;
	matrix[COLLIDER_ENEMY_FEET][COLLIDER_PLAYER_BLOCK] = false;
	matrix[COLLIDER_ENEMY_FEET][COLLIDER_ENEMY_BLOCK] = false;
	matrix[COLLIDER_ENEMY_FEET][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_ENEMY_FEET][COLLIDER_ENEMY] = false;
	matrix[COLLIDER_ENEMY_FEET][COLLIDER_PLAYER_WEAKATTACK] = true;
	matrix[COLLIDER_ENEMY_FEET][COLLIDER_PLAYER_MIDATTACK] = true;
	matrix[COLLIDER_ENEMY_FEET][COLLIDER_PLAYER_STRONGATTACK] = true;
	matrix[COLLIDER_ENEMY_FEET][COLLIDER_ENEMY_WEAKATTACK] = false;
	matrix[COLLIDER_ENEMY_FEET][COLLIDER_ENEMY_MIDATTACK] = false;
	matrix[COLLIDER_ENEMY_FEET][COLLIDER_ENEMY_STRONGATTACK] = false;
	matrix[COLLIDER_ENEMY_FEET][COLLIDER_ENEMY_BODY] = false;
	matrix[COLLIDER_ENEMY_FEET][COLLIDER_ENEMY_HEAD] = false;
	matrix[COLLIDER_ENEMY_FEET][COLLIDER_ENEMY_FEET] = false;

	//P2 BLOCK (YELLOW)

	matrix[COLLIDER_ENEMY_BLOCK][COLLIDER_PLAYER_BODY] = false;
	matrix[COLLIDER_ENEMY_BLOCK][COLLIDER_PLAYER_HEAD] = false;
	matrix[COLLIDER_ENEMY_BLOCK][COLLIDER_PLAYER_FEET] = false;
	matrix[COLLIDER_ENEMY_BLOCK][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_ENEMY_BLOCK][COLLIDER_ENEMY] = false;
	matrix[COLLIDER_ENEMY_BLOCK][COLLIDER_PLAYER_WEAKATTACK] = true;
	matrix[COLLIDER_ENEMY_BLOCK][COLLIDER_PLAYER_MIDATTACK] = true;
	matrix[COLLIDER_ENEMY_BLOCK][COLLIDER_PLAYER_STRONGATTACK] = true;
	matrix[COLLIDER_ENEMY_BLOCK][COLLIDER_ENEMY_WEAKATTACK] = false;
	matrix[COLLIDER_ENEMY_BLOCK][COLLIDER_ENEMY_MIDATTACK] = false;
	matrix[COLLIDER_ENEMY_BLOCK][COLLIDER_ENEMY_STRONGATTACK] = false;
	matrix[COLLIDER_ENEMY_BLOCK][COLLIDER_ENEMY_BODY] = false;
	matrix[COLLIDER_ENEMY_BLOCK][COLLIDER_ENEMY_HEAD] = false;
	matrix[COLLIDER_ENEMY_BLOCK][COLLIDER_ENEMY_FEET] = false;


	//P2 BLOCK_CROUCH (YELLOW)

	matrix[COLLIDER_ENEMY_BLOCK_CROUCH][COLLIDER_PLAYER_BODY] = false;
	matrix[COLLIDER_ENEMY_BLOCK_CROUCH][COLLIDER_PLAYER_HEAD] = false;
	matrix[COLLIDER_ENEMY_BLOCK_CROUCH][COLLIDER_PLAYER_FEET] = false;
	matrix[COLLIDER_ENEMY_BLOCK_CROUCH][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_ENEMY_BLOCK_CROUCH][COLLIDER_ENEMY] = false;
	matrix[COLLIDER_ENEMY_BLOCK_CROUCH][COLLIDER_PLAYER_WEAKATTACK] = true;
	matrix[COLLIDER_ENEMY_BLOCK_CROUCH][COLLIDER_PLAYER_MIDATTACK] = true;
	matrix[COLLIDER_ENEMY_BLOCK_CROUCH][COLLIDER_PLAYER_STRONGATTACK] = true;
	matrix[COLLIDER_ENEMY_BLOCK_CROUCH][COLLIDER_ENEMY_WEAKATTACK] = false;
	matrix[COLLIDER_ENEMY_BLOCK_CROUCH][COLLIDER_ENEMY_MIDATTACK] = false;
	matrix[COLLIDER_ENEMY_BLOCK_CROUCH][COLLIDER_ENEMY_STRONGATTACK] = false;
	matrix[COLLIDER_ENEMY_BLOCK_CROUCH][COLLIDER_ENEMY_BODY] = false;
	matrix[COLLIDER_ENEMY_BLOCK_CROUCH][COLLIDER_ENEMY_HEAD] = false;
	matrix[COLLIDER_ENEMY_BLOCK_CROUCH][COLLIDER_ENEMY_FEET] = false;


	/*
	matrix[COLLIDER_WALL][COLLIDER_ENEMY_BODY] = false;
	matrix[COLLIDER_WALL][COLLIDER_PLAYER] = true;
	matrix[COLLIDER_WALL][COLLIDER_ENEMY] = true;
	matrix[COLLIDER_WALL][COLLIDER_PLAYER_SHOT] = false;
	matrix[COLLIDER_WALL][COLLIDER_ENEMY_SHOT] = false;
	matrix[COLLIDER_WALL][COLLIDER_PLAYER_BODY] = false;
	//matrix[COLLIDER_WALL][COLLIDER_WALL] = false;*/
}

// Destructor
ModuleCollision::~ModuleCollision()
{}

update_status ModuleCollision::PreUpdate()
{
	// Remove all colliders scheduled for deletion
	p2List_item<Collider*>* tmp = colliders.getFirst();
	p2List_item<Collider*>* tmp2;

	while (tmp != NULL)
	{
		tmp2 = tmp->next;
		if (tmp->data->to_delete == true)
		{
			delete tmp->data;
			colliders.del(tmp);
		}
		tmp = tmp2;
	}

	return UPDATE_CONTINUE;
}

// Called before render is available
update_status ModuleCollision::Update()
{
	p2List_item<Collider*>* tmp = colliders.getFirst();

	Collider* c1;
	Collider* c2;

	while (tmp != NULL)
	{
		c1 = tmp->data;

		// Debug ---
		if (debug)
			DrawDebug(c1);

		p2List_item<Collider*>* tmp2 = tmp->next; // avoid checking collisions already checked
		while (tmp2 != NULL)
		{
			c2 = tmp2->data;

			if (c1->CheckCollision(c2->rect) == true)
			{
				if (matrix[c1->type][c2->type] && c1->callback)
					c1->callback->OnCollision(c1, c2);

				if (matrix[c2->type][c1->type] && c2->callback)
					c2->callback->OnCollision(c2, c1);
			}

			tmp2 = tmp2->next;
		}

		tmp = tmp->next;
	}



	// Debug ---
	if (App->input->GetKey(SDL_SCANCODE_F1) == KEY_DOWN)
		debug = !debug;

	return UPDATE_CONTINUE;
}

void ModuleCollision::DrawDebug(Collider* col)
{
	Uint8 alpha = 80;
	switch (col->type)
	{
	case COLLIDER_NONE:
		App->renderer->DrawQuad(col->rect, 255, 255, 255, alpha);
		break;
	case COLLIDER_PLAYER_BODY:
		App->renderer->DrawQuad(col->rect, 0, 0, 255, alpha);
		break;
	case COLLIDER_PLAYER_HEAD:
		App->renderer->DrawQuad(col->rect, 0, 0, 255, alpha);
		break;
	case COLLIDER_PLAYER_FEET:
		App->renderer->DrawQuad(col->rect, 0, 0, 255, alpha);
		break;
	case COLLIDER_PLAYER_BLOCK:
		App->renderer->DrawQuad(col->rect, 255, 255, 0, alpha);
		break;
	case COLLIDER_PLAYER_BLOCK_CROUCH:
		App->renderer->DrawQuad(col->rect, 255, 255, 0, alpha);
		break;
	case COLLIDER_PLAYER:
		App->renderer->DrawQuad(col->rect, 0, 255, 0, alpha);
		break;
	case COLLIDER_ENEMY_BODY:
		App->renderer->DrawQuad(col->rect, 0, 0, 255, alpha);
		break;
	case COLLIDER_ENEMY_HEAD:
		App->renderer->DrawQuad(col->rect, 0, 0, 255, alpha);
		break;
	case COLLIDER_ENEMY_FEET:
		App->renderer->DrawQuad(col->rect, 0, 0, 255, alpha);
		break;
	case COLLIDER_ENEMY_BLOCK:
		App->renderer->DrawQuad(col->rect, 255, 255, 0, alpha);
		break;
	case COLLIDER_ENEMY_BLOCK_CROUCH:
		App->renderer->DrawQuad(col->rect, 255, 255, 0, alpha);
		break;
	case COLLIDER_ENEMY:
		App->renderer->DrawQuad(col->rect, 0, 255, 0, alpha);
		break;
	case COLLIDER_PLAYER_WEAKATTACK:
		App->renderer->DrawQuad(col->rect, 255, 0, 0, alpha);
		break;
	case COLLIDER_PLAYER_MIDATTACK:
		App->renderer->DrawQuad(col->rect, 255, 0, 0, alpha);
		break;
	case COLLIDER_PLAYER_STRONGATTACK:
		App->renderer->DrawQuad(col->rect, 255, 0, 0, alpha);
		break;
	case COLLIDER_ENEMY_WEAKATTACK:
		App->renderer->DrawQuad(col->rect, 255, 0, 0, alpha);
		break;
	case COLLIDER_ENEMY_MIDATTACK:
		App->renderer->DrawQuad(col->rect, 255, 0, 0, alpha);
		break;
	case COLLIDER_ENEMY_STRONGATTACK:
		App->renderer->DrawQuad(col->rect, 255, 0, 0, alpha);
		break;
	}

}

// Called before quitting
bool ModuleCollision::CleanUp()
{
	LOG("Freeing all colliders");

	p2List_item<Collider*>* item = colliders.getLast();

	while (item != NULL)
	{
		delete item->data;
		item = item->prev;
	}

	colliders.clear();
	return true;
}

Collider* ModuleCollision::AddCollider(SDL_Rect rect, COLLIDER_TYPE type, Module* callback)
{
	Collider* ret = new Collider(rect, type, callback);
	colliders.add(ret);
	return ret;
}

// -----------------------------------------------------

bool Collider::CheckCollision(SDL_Rect r) const
{
	return (rect.x < r.x + r.w &&
		rect.x + rect.w > r.x &&
		rect.y < r.y + r.h &&
		rect.h + rect.y > r.y);
}