#include <stdio.h>
#include <string.h>
#pragma once

//-- States 


enum PLAYER_states
{
	ST_UNKNOWN,

	ST_IDLE,
	ST_WALK_FORWARD,
	ST_WALK_BACKWARD,
	ST_JUMP_NEUTRAL,
	ST_JUMP_FORWARD,
	ST_JUMP_BACKWARD,
	ST_CROUCH,

	ST_PUNCH_STANDING_LOW,
	ST_PUNCH_STANDING_MID,
	ST_PUNCH_STANDING_HIGH,

	ST_KICK_STANDING_LOW,
	ST_KICK_STANDING_MID,
	ST_KICK_STANDING_HIGH,

	ST_PUNCH_NEUTRAL_JUMP_LOW,
	ST_PUNCH_NEUTRAL_JUMP_MID,
	ST_PUNCH_NEUTRAL_JUMP_HIGH,

	ST_KICK_NEUTRAL_JUMP_LOW,
	ST_KICK_NEUTRAL_JUMP_MID,
	ST_KICK_NEUTRAL_JUMP_HIGH,

	ST_PUNCH_FORWARD_JUMP_LOW,
	ST_PUNCH_FORWARD_JUMP_MID,
	ST_PUNCH_FORWARD_JUMP_HIGH,

	ST_KICK_FORWARD_JUMP_LOW,
	ST_KICK_FORWARD_JUMP_MID,
	ST_KICK_FORWARD_JUMP_HIGH,

	ST_PUNCH_BACKWARD_JUMP_LOW,
	ST_PUNCH_BACKWARD_JUMP_MID,
	ST_PUNCH_BACKWARD_JUMP_HIGH,

	ST_KICK_BACKWARD_JUMP_LOW,
	ST_KICK_BACKWARD_JUMP_MID,
	ST_KICK_BACKWARD_JUMP_HIGH,

	ST_PUNCH_CROUCH_LOW,
	ST_PUNCH_CROUCH_MID,
	ST_PUNCH_CROUCH_HIGH,

	ST_KICK_CROUCH_LOW,
	ST_KICK_CROUCH_MID,
	ST_KICK_CROUCH_HIGH,

	ST_HADOUKEN
};

enum PLAYER_inputs
{
	IN_LEFT_DOWN,
	IN_LEFT_UP,
	IN_RIGHT_DOWN,
	IN_RIGHT_UP,
	IN_LEFT_AND_RIGHT,
	IN_JUMP,
	IN_CROUCH_UP,
	IN_CROUCH_DOWN,
	IN_JUMP_AND_CROUCH,
	IN_PUNCH_LOW,
	IN_PUNCH_MID,
	IN_PUNCH_HIGH,
	IN_KICK_LOW,
	IN_KICK_MID,
	IN_KICK_HIGH,
	IN_JUMP_FINISH,
	IN_KICK_FINISH,
	IN_HADOUKEN_START,
	IN_HADOUKEN_FINISH,
	IN_PUNCH_FINISH
};

